### PR TITLE
Bad http client initialization

### PR DESCRIPTION
**Pull request by nm0s**
[HTTPClient#initialize]() prefers keyword arguments. When passing a single argument it is interpreted as the http proxy address. This overrides the http_proxy environment variable, and, makes debugging difficult.

This fixes the HTTPClient initialization.

Maybe after merging https://github.com/OpenRefine/refine-ruby/pull/3 this diff will be cleaner.

### CODE REVIEW

**Comment by ostephens** [comment]
You could try contacting https://twitter.com/denormalize

If you are interested in actively developing the Ruby library and can't get a response from the previous committers, then probably a fork of the original repo is your best bet - we would be happy to link to an updated version of the library if you provide one in the future.

**Comment by nm0s** [comment]
Thanks, we'll try with Max and get back to you.

**Comment by thadguidry** [comment]
@nm0s Max Ogden can be reached here: https://maxogden.com/contact.html
and via his gmail maxosmail@gmail.com

**Comment by wetneb** [comment]
Hi @hand-of-distillytics,
This is amazing! I will update the README to point to your fork.

**Pull request closed without merging**
